# Bài thực hành 4
### Môn: Linear Algebra

In [1]:
import numpy as np
from scipy import linalg
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

In [2]:
# Phương pháp khử Gauss - Jordan
def gauss_jordan(A):
    m,n = A.shape
    pivots=[]
    s=-1
    for j in range(n):
        col = A[:,j].copy()
        for i in pivots:
            col[i] = 0
        col = np.abs(col)
        pivot_arg = np.argmax(col)
        pivot = A[pivot_arg,j]
        if col[pivot_arg]!=0 and s<m-1:
            s+=1
            pivots.append(s)
            A[pivot_arg,:] = 1/pivot*A[pivot_arg,:]
            row_swap = A[s,:].copy()
            A[s,:] = A[pivot_arg,:]
            A[pivot_arg,:] = row_swap
            for i in range(m):
                if i!=s:
                    A[i,:] -= A[i,j]*A[s,:]

### Bài tập 1
Cho hai không gian $U_1$ và $U_2$, trong đó $U_1$ được sinh bởi các cột của ma trận ${\bf A}_1$, $U_2$ được sinh bởi các cột của ma trận ${\bf A}_2$ với

$${\bf A}_1=\left[\begin{matrix}
1 & 0 & 1\\
1 & -2 & -1\\
2 & 1 & 3\\
1 & 0 & 1
\end{matrix}\right],\ 
{\bf A}_2=\left[\begin{matrix}
3 & -3 & 0\\
1 & 2 & 3\\
7 & -5 & 2\\
3 & -1 & 2
\end{matrix}\right]$$

Xác định một cơ sở và số chiều của các không gian véc tơ sau đây:
* $U_1$, $U_2$.
* $U_3=U_1+U_2=\{x=x_1+x_2\,:\,x_1\in U_1,\,x_2\in U_2\}$.
* $U_4=U_1\cap U_2=\{x\,:\,x\in U_1,\,x\in U_2\}$.

In [4]:
A1 = np.array([1,0, 1,1, -2, -1,2,1,3,1,0,1]).reshape(4,3)
A2 = np.array([3,-3,0,1,2,3,7,-5,2,3,-1,2]).reshape(4,3)
print(A1)
print(A2)

[[ 1  0  1]
 [ 1 -2 -1]
 [ 2  1  3]
 [ 1  0  1]]
[[ 3 -3  0]
 [ 1  2  3]
 [ 7 -5  2]
 [ 3 -1  2]]


In [5]:
#So chieu va co so cua cac khong gian vecto U1 = span(A1)
dim1 = np.linalg.matrix_rank(A1)
print(dim1)
U1 = np.around(linalg.lu(A1)[2],3)
print(U1)
print('Co so cua U1:', A1[:, 0:2], sep ='\n')

2
[[ 2.   1.   3. ]
 [ 0.  -2.5 -2.5]
 [ 0.   0.   0. ]]
Co so cua U1:
[[ 1  0]
 [ 1 -2]
 [ 2  1]
 [ 1  0]]


In [6]:
dim2 = np.linalg.matrix_rank(A2)
print(dim2)
U2 = np.around(linalg.lu(A2)[2],3)
print(U2)
print('Co so cua U2:', A2[:, 0:2], sep ='\n')

2
[[ 7.    -5.     2.   ]
 [ 0.     2.714  2.714]
 [ 0.     0.    -0.   ]]
Co so cua U2:
[[ 3 -3]
 [ 1  2]
 [ 7 -5]
 [ 3 -1]]


In [7]:
#So chieu va co so cua U3
A3 = np.hstack([A1,A2])
print(A3)

dim3 = np.linalg.matrix_rank(A3)
print('dim3:', dim3)
U3 = np.around(linalg.lu(A3)[2],3)
print(U3)
print('Co so cua U3: ', A3[:,0], A3[:, 1], A3[:,4])

[[ 1  0  1  3 -3  0]
 [ 1 -2 -1  1  2  3]
 [ 2  1  3  7 -5  2]
 [ 1  0  1  3 -1  2]]
dim3: 3
[[ 2.   1.   3.   7.  -5.   2. ]
 [ 0.  -2.5 -2.5 -2.5  4.5  2. ]
 [ 0.   0.   0.   0.  -1.4 -1.4]
 [ 0.   0.   0.   0.   2.   2. ]]
Co so cua U3:  [1 1 2 1] [ 0 -2  1  0] [-3  2 -5 -1]


In [9]:
x = np.array([-1,-0.444,0.111,0.667,1.222,1.778,2.333,])
x

array([-1.   , -0.444,  0.111,  0.667,  1.222,  1.778,  2.333])

### Bài tập 2
Cho các đa thức: 
$${\bf p}_1(x)=1+x,\,{\bf p}_2(x)=1-x,\,{\bf p}_3(x)=4$$
$${\bf p}_4(x)=1+x^2,\,{\bf p}_5(x)=1+2x+x^2$$

Gọi $H$ là không gian con của $\mathbb{P}_5$ sinh bởi tập $S=\{{\bf p}_1,{\bf p}_2,{\bf p}_3,{\bf p}_4,{\bf p}_5\}$.

* Hãy tìm một cơ sở và số chiều của $H$.
* Tìm tọa độ của ${\bf q}=3-2x+x^2\in H$ theo cơ sở tìm được.

### Bài 3
Trong xử lý tín hiệu số, phương trình sai phân cấp $n$:

$$y_{k+3}-2y_{k+2}+9y_{k+1}-18y_k=z_k$$

mô tả một bộ lọc tuyến tính với $\{y_k\}$ là tín hiệu vào và $\{z_k\}$ là tín hiệu ra. Trường hợp $z_k=0$ phương trình được gọi là thuần nhất. Tập tín hiệu vào $\{y_k\}$ thoả mãn phương trình thuần nhất là một không gian véc tơ 3 chiều $H$. Xét tập tín hiệu 

$$(\mathcal{B})=\left\{2^k,\,3^k\sin\left(\frac{k\pi}{2}\right),\,3^k\cos\left(\frac{k\pi}{2}\right)\right\}$$

* Chứng minh $(\mathcal{B})$ gồm các nghiệm của phương trình thuần nhất.
* Chứng minh $(\mathcal{B})$ là một cơ sở của $H$.