## <img src ='Pic\logo.jpg' width='500px'>


<div align="center">

# KHÓA HỌC: LẬP TRÌNH PYTHON CƠ BẢN

</div>

-----
Bài 5 - Làm việc với Thư viện NumPy - Phần 02
----
Giảng Viên: Đặng Văn Nam

Email: namdv@aiacademy.edu.vn

**NỘI DUNG BÀI 5:**
1. **Chuyển đổi Vector, Array**
    * Reshape, Ravel, Concatenate, Split, Hsplit, Vsplit, Flip
2. **Tính toán trên mảng**
    * Arithmetic operators | Abs | Trigonometric | Exponents|logarithms | Round 
3. **Sắp xếp các phần tử trong mảng (sort)**
    * Sắp xếp Vector| Sắp xếp Matrix
4. **Tìm kiếm các phần tử trong mảng (where)**
5. **Ma trận vuông**
    * det(A)| A-1 | diagonal | Matrix below diagonal | trace of matrix|Eigen
6. **Phép toán trên 2 ma trận**
    * nq.equal| np.add | np.subtract | np.dot (@)
7. **Rank(A), A.T**

In [1]:
#Gọi các thư viện sử dụng
import numpy as np

## 1) Kết hợp, chuyển đổi vector, matrix
---
### 1.1) reshape
<img src='Pic\reshape.png' width = '500px'>

In [2]:
# Phương thức a.reshape(m,n)
vector_a = np.array([5,7,2,9,10,15,2,9,2,17,28,16],dtype=np.int16)
print(vector_a)
print('Số phần tử của vector:', vector_a.size)

[ 5  7  2  9 10 15  2  9  2 17 28 16]
Số phần tử của vector: 12


In [3]:
#Chuyển đổi vector về matrix (n x m)
#Lưu ý: matrix.size =vector.size
matrix_a = vector_a.reshape((3,4))
print('Reshape về matrix: 3 x 4')
print(matrix_a)
print('Số phần tử của matrix_a:',matrix_a.size)

Reshape về matrix: 3 x 4
[[ 5  7  2  9]
 [10 15  2  9]
 [ 2 17 28 16]]
Số phần tử của matrix_a: 12


In [4]:
print('Reshape về matrix: 2 x 6')
matrix_b = vector_a.reshape((6,2))
print(matrix_b)
print('Số phần tử của matrix_b:',matrix_b.size)

Reshape về matrix: 2 x 6
[[ 5  7]
 [ 2  9]
 [10 15]
 [ 2  9]
 [ 2 17]
 [28 16]]
Số phần tử của matrix_b: 12


In [5]:
#sắp xếp thứ tự các phần tử khi reshape array
a1 = np.arange(1,13)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
#order ='C': default - reshape phần tử theo hàng
matrix_a1 = a1.reshape((3,4),order='C')
print(matrix_a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
#order ='F': reshape phần tử theo cột
matrix_a2 = a1.reshape((3,4),order='F')
print(matrix_a2)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [8]:
#Sử dụng tham số -1 để tự động tính toán số hàng (hoặc số cột)
A = np.random.randint(0,100,80)
A

array([95, 91, 85, 41, 92, 34, 66, 64, 78, 89, 22,  0,  0, 36, 69, 67, 38,
       65, 77, 20, 13, 49,  0,  1, 77, 14,  8, 97, 16, 99,  1, 21, 51, 14,
       52, 54,  3, 90, 35, 47, 70, 37, 15, 58, 10, 84, 23,  4, 46, 53, 20,
       47, 47, 16, 46, 22, 72, 25, 66, 98, 51, 77, 67, 66, 43, 68, 97, 55,
       54, 92, 42, 23,  3, 67, 71, 44, 45, 87, 68, 97])

In [9]:
#Tự động tính toán số cột
A1 = A.reshape(8,-1)
print(A1)
print(A1.shape)

[[95 91 85 41 92 34 66 64 78 89]
 [22  0  0 36 69 67 38 65 77 20]
 [13 49  0  1 77 14  8 97 16 99]
 [ 1 21 51 14 52 54  3 90 35 47]
 [70 37 15 58 10 84 23  4 46 53]
 [20 47 47 16 46 22 72 25 66 98]
 [51 77 67 66 43 68 97 55 54 92]
 [42 23  3 67 71 44 45 87 68 97]]
(8, 10)


In [10]:
#Tự động tính toán số hàng
A2 = A.reshape(-1,10)
print(A2)

[[95 91 85 41 92 34 66 64 78 89]
 [22  0  0 36 69 67 38 65 77 20]
 [13 49  0  1 77 14  8 97 16 99]
 [ 1 21 51 14 52 54  3 90 35 47]
 [70 37 15 58 10 84 23  4 46 53]
 [20 47 47 16 46 22 72 25 66 98]
 [51 77 67 66 43 68 97 55 54 92]
 [42 23  3 67 71 44 45 87 68 97]]


In [11]:
A2.shape

(8, 10)

In [12]:
#Thay đổi kích thước ma trận
A3=A2.reshape(4,-1)
print(A3)
A3.shape

[[95 91 85 41 92 34 66 64 78 89 22  0  0 36 69 67 38 65 77 20]
 [13 49  0  1 77 14  8 97 16 99  1 21 51 14 52 54  3 90 35 47]
 [70 37 15 58 10 84 23  4 46 53 20 47 47 16 46 22 72 25 66 98]
 [51 77 67 66 43 68 97 55 54 92 42 23  3 67 71 44 45 87 68 97]]


(4, 20)

### 1.2) Flatten | ravel array
---
**Phương thức: ravel sử dụng để chuyển Matrix thành Vector**
<img src='Pic\ravel.png' width = '200px'>


In [13]:
#Chuyển đổi từ Matrix --> Vector

a1_2d = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print('Matrix: \n', a1_2d)

Matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
print('a) ravel by row (default order=\'C\')')
print(a1_2d.ravel()) 

a) ravel by row (default order='C')
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
print('b) ravel by column (order=\'F\')')
print(a1_2d.ravel(order='F'))

b) ravel by column (order='F')
[ 1  5  9  2  6 10  3  7 11  4  8 12]


### 5.3) Concatenate array
---
**Phương thức: Concatenate sử dụng để kết hợp các vector, array lại với nhau**
<img src='Pic\concat1.png' width = '400px'>

In [16]:
#1) Phương thức: Concatenate sử dụng để kết hợp các vectorlại với nhau
#Khởi Tạo vector
x = np.full((5),1)
y = np.full((5),9)

print('Vector x:', x)
print('Vector y:', y)

Vector x: [1 1 1 1 1]
Vector y: [9 9 9 9 9]


In [17]:
#Ghép 2 vector 
xy = np.concatenate([x, y])
print('Vector xy:',xy)

Vector xy: [1 1 1 1 1 9 9 9 9 9]


In [18]:
#2) Phương thức: Concatenate sử dụng để kết hợp các ma trận lại với nhau
#Khởi Tạo ma trận
x = np.full((3,4),1)
y = np.full((3,4),9)

print('Ma trận x:\n', x)
print('Ma trận y:\n', y)

Ma trận x:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Ma trận y:
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [19]:
#Ghép 2 ma trận theo hàng axis=0 (Default)
xy_row = np.concatenate([x, y],axis=0)
print('Ma trận xy (theo hàng):\n',xy_row)

Ma trận xy (theo hàng):
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [20]:
#Ghép 2 ma trận theo cột axis=1
xy_col = np.concatenate([x, y],axis=1)
print('Ma trận xy (theo cột):\n',xy_col)

Ma trận xy (theo cột):
 [[1 1 1 1 9 9 9 9]
 [1 1 1 1 9 9 9 9]
 [1 1 1 1 9 9 9 9]]


In [21]:
#Ghép 2 ma trận thành 1 vector
xy_none = np.concatenate([x, y],axis=None)
print('Ma trận xy:\n',xy_none)

Ma trận xy:
 [1 1 1 1 1 1 1 1 1 1 1 1 9 9 9 9 9 9 9 9 9 9 9 9]


### 5.3) Split array
---
**Phương thức: Split sử dụng để phân tách các vector, ma trận thành các vector, ma trận con**
<img src='Pic\split.png'>

In [22]:
#Split với Vector
import numpy as np
x = np.arange(0,10)
print(x)
print(x.size)


[0 1 2 3 4 5 6 7 8 9]
10


In [23]:
#Tách vector x thành 2 vector 
#có số phần tử bằng nhau
x1, x2 = np.split(x, 2)
print(x1, x2)

[0 1 2 3 4] [5 6 7 8 9]


In [24]:
#Tách vector x thành 2 vector 
#vector 1 có 4 phần tử
x11, x22 = np.split(x, [7])
print(x11, x22)

[0 1 2 3 4 5 6] [7 8 9]


In [25]:
import numpy as np
x = np.arange(1,10)
print(x)

#Tách vector x thành 3 vector 
#tại các vị trí 2 và 6
x1, x2, x3 = np.split(x, [2,6])
print(x1, x2, x3)

[1 2 3 4 5 6 7 8 9]
[1 2] [3 4 5 6] [7 8 9]


In [26]:
#Split với Ma trận
a = np.array([(1,2,3,4,5), 
              (6,7,8,9,10), 
              (11,12,13,14,15), 
              (16,17,18,19,20)])
print(a)
print('-----------------------------')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-----------------------------


In [27]:
#split theo row
upper, lower = np.vsplit(a, 2)
print(upper)
print('-----------------------------')
print(lower)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------------------------
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [28]:
print(a)
print('-----------------------------')
#split theo col, Tách thành 3 ma trận
#Ma trận đầu chứ 2 cột dữ liệu
a1, a2, a3 = np.hsplit(a, (2,3))
print(a1)
print('-----------------------------')
print(a2)
print('-----------------------------')
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-----------------------------
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
-----------------------------
[[ 3]
 [ 8]
 [13]
 [18]]
-----------------------------
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


### 5.5) Flip array
---
**Phương thức: Flip sử dụng lật ngược ma trận theo hàng, cột**

In [29]:
#A) Lật vector
V = np.linspace(1,30,30,dtype=np.int8)
print(V)
print('----------------------------------------------')
V1 = np.flip(V)
print(V1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
----------------------------------------------
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1]


In [30]:
#B) Lật ma trận
#Tạo ma trận A làm ví dụ
A = np.linspace(1,25,25,dtype=np.int8).reshape(5,5)
print('Ma trận ban đầu: \n',A)

Ma trận ban đầu: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [31]:
#Lật ma trận theo cột
#A1 = np.flip(A,1) 
#Tương đương với
A1 = np.fliplr(A)
print('Lật ma trận theo cột: \n',A1)

Lật ma trận theo cột: 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [32]:
#Lật ma trận theo hàng
#A2 = np.flip(A,0) 
#Tương đương với
A2 = np.flipud(A)
print('Lật ma trận theo hàng: \n',A2)

Lật ma trận theo hàng: 
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## THỰC HÀNH SỐ 1:
---
**Yêu cầu: Tạo một vector gồm 30 phần tử, có giá trị tăng dần từ 1 đến 30**

Chỉ sử dụng các phương thức reshape, ravel, split…tách Vector a ở trên thành 3 vector con bao gồm:

1. a_lẻ: chứa các phần tử là số lẻ; 
2. a_chan: chứa các phần tử là số chẵn.
3. a_3: chứa các phần tử chia hết cho 3

In [ ]:
#{HỌC VIÊN VIẾT CODE VÀO ĐÂY}





## 2) TÍNH TOÁN GIÁ TRỊ CÁC PHẦN TỬ TRONG MẢNG SỬ DỤNG NUMPY
---
### 2.1) Các phép tính toán học

In [33]:
import numpy as np
x = np.arange(8)
print("x     =", x)
print('----------------------------------')
#Các phép toán đã giới thiệu trong buổi 01
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print(" -x    =", -x)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)
print("x % 2  =", x % 2)
print("x ^ 3  =", x**3)

x     = [0 1 2 3 4 5 6 7]
----------------------------------
x + 5  = [ 5  6  7  8  9 10 11 12]
x - 5  = [-5 -4 -3 -2 -1  0  1  2]
 -x    = [ 0 -1 -2 -3 -4 -5 -6 -7]
x * 2  = [ 0  2  4  6  8 10 12 14]
x / 2  = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]
x // 2 = [0 0 1 1 2 2 3 3]
x % 2  = [0 1 0 1 0 1 0 1]
x ^ 3  = [  0   1   8  27  64 125 216 343]


In [34]:
print("x      =", x)
print('---------------------------------')
#Sử dụng các phương thức của NumPy
print("x + 5  =", np.add(x,5))
print("x - 5  =", np.subtract(x, 5))
print("-x     =", np.negative(x))
print("x * 2  =", np.multiply(x,2))
print("x / 2  =", np.divide(x,2))
print("x // 2 =", np.floor_divide(x, 2))
print("x % 2  =", np.mod(x,2))
print("x ^ 3  =", np.power(x,3))

x      = [0 1 2 3 4 5 6 7]
---------------------------------
x + 5  = [ 5  6  7  8  9 10 11 12]
x - 5  = [-5 -4 -3 -2 -1  0  1  2]
-x     = [ 0 -1 -2 -3 -4 -5 -6 -7]
x * 2  = [ 0  2  4  6  8 10 12 14]
x / 2  = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]
x // 2 = [0 0 1 1 2 2 3 3]
x % 2  = [0 1 0 1 0 1 0 1]
x ^ 3  = [  0   1   8  27  64 125 216 343]


### 2.2) Abs|Trigonometric Functions in NumPy
---

In [35]:
x = np.array([-2, -1, 0, 1, 2])
print(x)
print('----------------------')
print(np.abs(x))
print(np.absolute(x))


[-2 -1  0  1  2]
----------------------
[2 1 0 1 2]
[2 1 0 1 2]


In [36]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print('------------------------------------------')
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))


theta      =  [0.         1.57079633 3.14159265]
------------------------------------------
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [37]:
x = [-1, 0, 1]
print("x         = ", x)
print('----------------------------------')
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
----------------------------------
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## 2.3) Logarithmic and Exponential Functions
---

In [38]:
x = np.array([1, 2, 3])

print("x     =", x)
print('---------------------------')
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1 2 3]
---------------------------
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [39]:
x = np.array([1, 2, 4, 100])

print("x        =", x)
print('---------------------------')
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [  1   2   4 100]
---------------------------
ln(x)    = [0.         0.69314718 1.38629436 4.60517019]
log2(x)  = [0.         1.         2.         6.64385619]
log10(x) = [0.         0.30103    0.60205999 2.        ]


## 4.4 Rounding Functions
---

In [40]:
import numpy as np  
arr = np.array([20.8994,67.89899,54.43409]) 

print(arr)
print('----------------------------------')
#1) Làm tròn tới 1 số sau dấu ,
print(np.around(arr,3))

[20.8994  67.89899 54.43409]
----------------------------------
[20.899 67.899 54.434]


In [41]:
#2)Làm tròn tới 2 số sau dấu ,
print(np.around(arr,2))

[20.9  67.9  54.43]


In [42]:
#3)Làm tròn xuống số nguyên gần nhất
print(np.floor(arr))

[20. 67. 54.]


In [43]:
#4)Làm tròn lên số nguyên gần nhất
print(np.ceil(arr))

[21. 68. 55.]


## 3) Sắp xếp các phần tử trong mảng
---
np.sort: Thực hiện sắp xếp các phần tử trong mảng theo thứ tự tăng dần (hàng, cột)
<img src='Pic\sort.png' width='500px'>

In [44]:
#3.1) Sắp xếp các phần tử trong một vector
a = np.random.randint(1,33,15)

print('Vector ban đầu:\n', a)

Vector ban đầu:
 [31 25 31  2  1  8  5 11 16  1 14 28 13 23 10]


In [45]:
#Sắp xếp vector a tăng dần
a_sort = np.sort(a)
print('Vector sắp xếp tăng dần: \n',a_sort)

Vector sắp xếp tăng dần: 
 [ 1  1  2  5  8 10 11 13 14 16 23 25 28 31 31]


In [46]:
#Sắp xếp vector a giảm dần:
#1) Lật vector a_sort để sắp xếp giảm dần
#b_sort = np.flip(a_sort)
#2) sử dụng -np.sort(-x)
b_sort = -np.sort(-a)
print('Vector sắp xếp giảm dần: \n',b_sort)

Vector sắp xếp giảm dần: 
 [31 31 28 25 23 16 14 13 11 10  8  5  2  1  1]


In [ ]:
#3.2) Sắp xếp các phần tử trong một Ma trận
#Tạo ma trận A làm ví dụ
A = np.random.randint(1,30,30).reshape(5,6)
print('Ma trận A:\n', A)

In [ ]:
#a) Sắp xếp theo hàng axis=0
a_sort1 = np.sort(A,axis=0)
print('Ma trận 1:\n', a_sort1)

In [ ]:
print(A)

In [ ]:
#b) Sắp xếp theo cột axis=1 | Default
a_sort2 = np.sort(A,axis=1)
print('Ma trận 2:\n', a_sort2)

In [ ]:
#c) Chuyển thành vector và sắp xếp các phần tử tăng dần theo hàng
v_sort = np.sort(A,axis=None)
print('Vector: \n', v_sort)

In [ ]:
#Sắp xếp tất cả các phần tử theo thứ tự tăng dần theo hàng
a_sort3 = np.sort(A, axis=None).reshape(A.shape[0],A.shape[1])
print('Ma trận 3:\n', a_sort3)

In [ ]:
#thuộc tính kind=‘quicksort’- Default, ‘mergesort’, ‘heapsort’, ‘stable’
a_sort1 = np.sort(A,axis=0, kind='mergesort')
print('Ma trận 1:\n', a_sort1)

## 4) Tìm kiếm các phần tử trong mảng
---
np.where: Thực hiện tìm kiếm các phần tử trong mảng

**a) Tìm kiếm trên vector:**

In [47]:
import numpy as np
x = np.array([17, 2, 11, 1, 9, 15, 1, 3, 8, 1, 12, 13, 5])
print(x)

[17  2 11  1  9 15  1  3  8  1 12 13  5]


In [48]:
#1) Tìm kiếm các phần tử có giá trị ==1
t1 = np.where(x==1)
print(t1)
print('1. Số phần tử thỏa mãn điều kiện = 1: ', t1[0].size)

(array([3, 6, 9], dtype=int64),)
1. Số phần tử thỏa mãn điều kiện = 1:  3


In [ ]:
#2)Tìm kiếm các phần tử có giá trị >10
t2 = np.where(x>10)
print(t2)
print('2. Số phần tử thỏa mãn điều kiện>10: ', t2[0].size)

In [ ]:
x

In [ ]:
#Tìm kiếm các phần tử có giá trị [5,12)
t3 = np.where((x>=5) & (x<12))
print(t3)
print('3.Số phần tử thỏa mãn điều kiện [5,12): ', t3[0].size)

**b) Tìm kiếm trên ma trận:**

In [49]:
#Khởi tạo ma trận arr
arr = np.array([(1, 2, 3, 4, 5, 4, 4),
                (7, 3, 4, 8, 9, 6, 7)])
print('Ma trận A: \n',arr)

Ma trận A: 
 [[1 2 3 4 5 4 4]
 [7 3 4 8 9 6 7]]


In [50]:
#Tìm kiếm phần tử > 4
x = np.where(arr >4)
print(x)
print('Số phần tử thỏa mãn điều kiện > 4:',x[0].size)

#Kết quả: array đầu tiên là chỉ số hàng, array thứ 2 là chỉ số cột.

(array([0, 1, 1, 1, 1, 1], dtype=int64), array([4, 0, 3, 4, 5, 6], dtype=int64))
Số phần tử thỏa mãn điều kiện > 4: 6


In [52]:
#Tìm kiếm và trả về kết quả với điều kiện đúng, sai
#Nếu Đúng thay bằng T, sai thay thế bằng F
x = np.where(arr >4,1,0)
print(arr)
print('----------------------------')
print(x)

[[1 2 3 4 5 4 4]
 [7 3 4 8 9 6 7]]
----------------------------
[[0 0 0 0 1 0 0]
 [1 0 0 1 1 1 1]]


# THỰC HÀNH SỐ 2:
---

**Yêu cầu 2.1: Đọc dữ liệu từ file Data_Excercise/Data_BMI.txt vào 2 vector tương ứng**
1. v_height: chứa dữ liệu chiều cao
2. v_Weight: Chứa dữ liệu cân nặng


In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






**Yêu cầu 2.2: Tạo vector v_height_m2 từ vector v_height theo yêu cầu sau:**
1. Chuyển đổi đơn vị của các phần tử từ cm sang m
2. Tính bình phương giá trị các phần tử

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






**Yêu cầu 2.3: Tính chỉ số BMI của 100 người ngày theo công thức bên dưới, chỉ số BMI được làm tròn tới 1 số sau dấu “,”. Lưu kết quả vào vector v_bmi**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






In [ ]:
#Tính chỉ số BMI
v_bmi = np.round(v_weight / v_height_m2,1)
print ('Chỉ số BMI:\n', v_bmi)

**Yêu cầu 2.4: Sắp xếp thứ tự các phần tử trong vector v_bmi theo chiều tăng dần, giảm dần**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






**Yêu cầu 2.5: Thống kê số lượng người theo từng mức dựa vào phân loại theo hình**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






## 5. MA TRẬN VUÔNG
---
### 5.1) det(a)

In [53]:
import numpy as np
a =np.array([( 1, 3, 1, 4),
             ( 3, 9, 5,15),
             ( 0, 2, 1, 1),
             ( 0, 4, 2, 3)])
print('Ma trận a:\n',a)
det_a =  np.linalg.det(a)
print('det(a) = ', det_a)

Ma trận a:
 [[ 1  3  1  4]
 [ 3  9  5 15]
 [ 0  2  1  1]
 [ 0  4  2  3]]
det(a) =  -3.999999999999999


In [ ]:
import numpy as np
b =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận b:\n',b)
det_b =  np.linalg.det(b)
print('det(b) = ', det_b)

In [ ]:
a =np.array([( 3, 0, 2,-1),
             ( 1, 2, 0,-2),
             ( 4, 0, 6,-3),
             ( 5, 0, 2, 0)])
det_a =  np.linalg.det(a)
print(det_a)

### 5.2) ma trận nghịch đảo
---

In [54]:
import numpy as np
m = np.array([(1, 2, 3),
              (0, 1, 4),
              (5, 6, 0)])


print(m)
det_m =  np.linalg.det(m)
print(det_m)
print('--------------------------')
#Xác định ma trận nghịc đảo của m
m1 = np.linalg.inv(m)
print(m1)
print('--------------------------')
print(np.dot(m,m1).astype(int))

[[1 2 3]
 [0 1 4]
 [5 6 0]]
0.9999999999999987
--------------------------
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
--------------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [55]:
#Trường hợp det(a) = 0; không tồn tại ma trận nghịch đảo.
import numpy as np
b =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận b:\n',b)
det_b =  np.linalg.det(b)
print('det(b) = ', det_b)

b1 = np.linalg.inv(b)

Ma trận b:
 [[ 1  2  3  4]
 [-2 -1  4  1]
 [ 3 -4 -5  6]
 [ 1  2  3  4]]
det(b) =  0.0


LinAlgError: Singular matrix

### 5.3) Đường chéo trong ma trận vuông
---
A) Lấy các phần tử trên đường chéo

In [56]:
A = np.random.randint(1,100,(10,10))
print(A)

[[95 54 39 56 91 53 64 44 37 93]
 [48 87 39 56 33 91 28 41 65 89]
 [15  7 78  7 37 19 53 43 39 34]
 [ 1 48 19 67 78 74 35 94 37 25]
 [ 1 41 88 73 85 22 48 91 24  4]
 [89 29 60 18 60 39  8 29 10 64]
 [43 28 22 59 65 11 34 64 51 59]
 [27 80 98  5 30 28 52 79 17 85]
 [32 32 12 28 18 86 72 42 89 77]
 [34 33 78 62 79 89 59 37 25 33]]


In [57]:
#Lấy các phần tử trên đường chéo chính của 
#ma trận vuông A
d_A = A.diagonal()
print(d_A)

[95 87 78 67 85 39 34 79 89 33]


In [58]:
#Lấy các phần tử nằm trên đường chéo chính
#của ma trận a 1 phần tử
d_A1 =  A.diagonal(3)
print(d_A1)

[56 33 19 35 91 10 59]


In [59]:
#Lấy các phần tử nằm dưới đường chéo chính
#của ma trận a 4 phần tử
d_A1 =  A.diagonal(-4)
print(d_A1)

[ 1 29 22  5 18 89]


**B) Lấy ma trận tam giác**

In [60]:
A

array([[95, 54, 39, 56, 91, 53, 64, 44, 37, 93],
       [48, 87, 39, 56, 33, 91, 28, 41, 65, 89],
       [15,  7, 78,  7, 37, 19, 53, 43, 39, 34],
       [ 1, 48, 19, 67, 78, 74, 35, 94, 37, 25],
       [ 1, 41, 88, 73, 85, 22, 48, 91, 24,  4],
       [89, 29, 60, 18, 60, 39,  8, 29, 10, 64],
       [43, 28, 22, 59, 65, 11, 34, 64, 51, 59],
       [27, 80, 98,  5, 30, 28, 52, 79, 17, 85],
       [32, 32, 12, 28, 18, 86, 72, 42, 89, 77],
       [34, 33, 78, 62, 79, 89, 59, 37, 25, 33]])

In [61]:
#MA TRẬN TAM GIÁC TRÊN
#ma trận A
d_A1 = np.triu(A)
print(d_A1)

[[95 54 39 56 91 53 64 44 37 93]
 [ 0 87 39 56 33 91 28 41 65 89]
 [ 0  0 78  7 37 19 53 43 39 34]
 [ 0  0  0 67 78 74 35 94 37 25]
 [ 0  0  0  0 85 22 48 91 24  4]
 [ 0  0  0  0  0 39  8 29 10 64]
 [ 0  0  0  0  0  0 34 64 51 59]
 [ 0  0  0  0  0  0  0 79 17 85]
 [ 0  0  0  0  0  0  0  0 89 77]
 [ 0  0  0  0  0  0  0  0  0 33]]


In [62]:
#MA TRẬN TAM GIÁC TRÊN
#Tạo ma trận là các phần tử trên đường chéo chính 
#của ma trận vuông A cách đường chéo chính
#về phía trên 2 đường
d_A1 = np.triu(A,4)
print(d_A1)

[[ 0  0  0  0 91 53 64 44 37 93]
 [ 0  0  0  0  0 91 28 41 65 89]
 [ 0  0  0  0  0  0 53 43 39 34]
 [ 0  0  0  0  0  0  0 94 37 25]
 [ 0  0  0  0  0  0  0  0 24  4]
 [ 0  0  0  0  0  0  0  0  0 64]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [63]:
#MA TRẬN TAM GIÁC TRÊN
#Tạo ma trận là các phần tử trên đường chéo chính 
#của ma trận vuông A cách đường chéo chính
#về phía dưới 3 đường
d_A1 = np.triu(A,-3)
print(d_A1)

[[95 54 39 56 91 53 64 44 37 93]
 [48 87 39 56 33 91 28 41 65 89]
 [15  7 78  7 37 19 53 43 39 34]
 [ 1 48 19 67 78 74 35 94 37 25]
 [ 0 41 88 73 85 22 48 91 24  4]
 [ 0  0 60 18 60 39  8 29 10 64]
 [ 0  0  0 59 65 11 34 64 51 59]
 [ 0  0  0  0 30 28 52 79 17 85]
 [ 0  0  0  0  0 86 72 42 89 77]
 [ 0  0  0  0  0  0 59 37 25 33]]


In [64]:
#MA TRẬN TAM GIÁC DƯỚI
#của ma trận vuông A
b_A1 = np.tril(A)
print(b_A1)

[[95  0  0  0  0  0  0  0  0  0]
 [48 87  0  0  0  0  0  0  0  0]
 [15  7 78  0  0  0  0  0  0  0]
 [ 1 48 19 67  0  0  0  0  0  0]
 [ 1 41 88 73 85  0  0  0  0  0]
 [89 29 60 18 60 39  0  0  0  0]
 [43 28 22 59 65 11 34  0  0  0]
 [27 80 98  5 30 28 52 79  0  0]
 [32 32 12 28 18 86 72 42 89  0]
 [34 33 78 62 79 89 59 37 25 33]]


In [65]:
b_A1 = np.tril(A,-3)
print(b_A1)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 1 41  0  0  0  0  0  0  0  0]
 [89 29 60  0  0  0  0  0  0  0]
 [43 28 22 59  0  0  0  0  0  0]
 [27 80 98  5 30  0  0  0  0  0]
 [32 32 12 28 18 86  0  0  0  0]
 [34 33 78 62 79 89 59  0  0  0]]


In [66]:
b_A1 = np.tril(A,4)
print(b_A1)

[[95 54 39 56 91  0  0  0  0  0]
 [48 87 39 56 33 91  0  0  0  0]
 [15  7 78  7 37 19 53  0  0  0]
 [ 1 48 19 67 78 74 35 94  0  0]
 [ 1 41 88 73 85 22 48 91 24  0]
 [89 29 60 18 60 39  8 29 10 64]
 [43 28 22 59 65 11 34 64 51 59]
 [27 80 98  5 30 28 52 79 17 85]
 [32 32 12 28 18 86 72 42 89 77]
 [34 33 78 62 79 89 59 37 25 33]]


**C) Trace of Matrix**

In [ ]:
A

In [67]:
#Tính trace của ma trận vuông A
trace_A = A.trace()
print('Trace of Matrix A: ',trace_A)

Trace of Matrix A:  686


In [ ]:
#Cách 2: Tính trace của ma trận vuông A
trace_A = A.diagonal().sum()
print('Trace of Matrix A: ',trace_A)

#### D) Eigenvector | Eigenvalues
---

In [ ]:
#Tìm giá trị riêng, vector riêng của vector A
A = np.array([(3, 4,-2),
              (1, 4,-1),
              (2, 6,-1)])
print(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
print('Eigenvalues: ', eigenvalues)
print('Eigenvectors: \n',eigenvectors)

In [ ]:
det_a =  np.linalg.det(A)
print('det(A) = ', det_a)

In [ ]:
#Kiểm tra
t = eigenvectors[:,0]
print(t)

In [ ]:
print(A@t)

In [ ]:
print(3*t)

In [ ]:
#Trường hợp det(A) = 0
import numpy as np
b =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận b:\n',b)
det_b =  np.linalg.det(b)
print('det(b) = ', det_b)

In [ ]:
#Trị riêng, vector riêng là số phức.
eigenvalues_b, eigenvectors_b = np.linalg.eig(b)
print('Eigenvalues: ', eigenvalues_b)
print('Eigenvectors: \n',eigenvectors_b)

## THỰC HÀNH SỐ 3:
---
**Yêu cầu 3.1: Sử dụng vector_weigth trong bài thực hành 2 chuyển về ma trận kích thước 10 x 10**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






**Yêu cầu 3.2: Cho biết ma trận weight có tồn tại ma trân nghịch đảo không? Nếu có hãy xác định ma trận weight-1 ?**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






**Yêu cầu 3.3: Tạo vector_diagonal chứa các phần tử trên đường chéo chính của ma trận weight, tính trace của ma trận weight.**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






**Yêu cầu 3.4: Tìm giá trị lớn nhất của ma trận đường chéo trên và ma trận đường chéo dưới không bao gồm các phần tử trên đường chéo chính**

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






## 6. Phép toán trên 2 mảng
---
<img src='Pic\math.png' width='500px'>

In [ ]:
# Thực hiện các phép toán giữa 2 biến array
# Yêu cầu: Số phần tử của hai mảng, ma trận phải bằng nhau
a=np.array((7,5,8,1))
print('Mảng a: ', a)
b=np.array((1,2,3,4))
print('Mảng b: ', b)

#Các phép toán trên 2 biến array
array_tong = a + b
print("Tổng mảng a + b:", array_tong)

array_hieu = a - b
print("Tổng mảng a - b:", array_hieu)

array_tich=a*b
print("Tích mảng a * b:", array_tich)

array_thuong=a/b
print("Tích mảng a / b:", array_thuong)

array_thuongnguyen=a//b
print("Thương nguyên mảng a // b:", array_thuongnguyen)

array_thuongdu=a%b
print("Thương dư của mảng a % b:", array_thuongdu)

In [ ]:
#PHép toán trên Ma trận
#Khởi tạo ma trận ví dụ:
a = np.random.randint(1,20,(3,5))
b = np.random.randint(1,20,(3,5))
print('Matrix a: \n',a)
print('Matrix b: \n',b)

In [ ]:
#1) So sánh 2 ma trận
equal_ab = np.equal(a,b)
#hoặc equal_ab = a==b

print(equal_ab)

In [ ]:
#Phép cộng 2 ma trận
sum_ab = np.add(a,b)
#hoặc sum_ab = a + b
print (sum_ab)

In [ ]:
#Phép trừ 2 ma trận
sub_ab = np.subtract(a,b)
#hoặc sub_ab = a - b
print (sub_ab)

In [ ]:
c = np.random.randint(1,20,(5,4))
print('Matrix a: \n',a)
print('Matrix c: \n',c)

In [ ]:
#3) Tích của 2 ma trận:
#a(mxn) x C(nxk) = AC(m,k)
#multi_ac = np.dot(a,c)
multi_ac1 = a@c
print(multi_ac1)

In [ ]:
#Lưu ý: Nếu sử dụng phép toán *, 
#thực hiện nhân từng phần tử của ma trận a và b theo từng vị trí
#a, b có cùng kích thước.

multi_ac = a*b
print(multi_ac)
print

In [ ]:
#Tích của 2 vector:
vector_a = np.random.randint(1,20,10)
vector_b = np.random.randint(1,20,10)
#Thực hiện tính tích của 2 vector
#Kết quả trả về một số
vector_ab = vector_a @ vector_b

print('Vector a:\n',vector_a)
print('Vector b:\n',vector_b)
print('Tích của hai vector:\n',vector_ab)

# THỰC HÀNH SỐ 4
---
**Yêu cầu 4.1: Chuyển vector_height, vector_weigth trong bài thực hành 2 về ma trận height, weight kích thước 10 x 10.**

Thực hiện các phép toán: So sánh; Cộng; Trừ; Nhân hai ma trận height và weighT

In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}






## 7. Rank(A); A.T
---
### 7.1) Hạng của ma trận

In [ ]:
A=np.array([(-1, 2, 0, 4, 5,-3),
            ( 3,-7, 2, 0, 1, 4),
            ( 2,-5, 2, 4, 6, 1),
            ( 4,-9, 2,-4,-4, 7)])
#Tìm hạng của ma trận A
rank_a = np.linalg.matrix_rank(A)
print(A)
print('Rank(A) = ', rank_a)

In [ ]:
#Hạng của ma trận 0
A_0 = np.zeros((4,5))
print(A_0)
rank = np.linalg.matrix_rank(A_0)
print('Rank(A_0) = ', rank)

In [ ]:
#Hạng của ma trận có các phần tử bằng nhau
A_cons = np.full((4,5),5)
print(A_cons)
rank_c = np.linalg.matrix_rank(A_cons)
print('Rank(A_cons) = ', rank_c)

In [ ]:
#Hạng của ma trận có det(A)=0
import numpy as np
B =np.array([( 1, 2, 3, 4),
             (-2,-1, 4, 1),
             ( 3,-4,-5, 6),
             ( 1, 2, 3, 4)])
print('Ma trận B1:\n',B)
det_b =  np.linalg.det(B)
print('det(B1) = ', det_b)
rank_b = np.linalg.matrix_rank(B)
print('Rank(B1) = ', rank_b)

In [ ]:
#Hạng của ma trận có det(A)#0
import numpy as np
B =np.array([( 1, 3, 1, 4),
             ( 3, 9, 5,15),
             ( 0, 2, 1, 1),
             ( 0, 4, 2, 3)])
print('Ma trận B2:\n',B)
det_b =  np.linalg.det(B)
print('det(B2) = ', round(det_b,2))
rank_b = np.linalg.matrix_rank(B)
print('Rank(B2) = ', rank_b)

### 7.2) Ma trận chuyển vị
---

In [ ]:
#MA TRẬN CHUYỂN VỊ
A=np.array([(-1, 2, 0, 4, 5,-3),
            ( 3,-7, 2, 0, 1, 4),
            ( 2,-5, 2, 4, 6, 1),
            ( 4,-9, 2,-4,-4, 7)])
#Tìm ma trận chuyển vị của A
A_T = A.T
print('Ma trận A:\n',A)
print('Ma trận chuyển vị của A:\n',A_T)

In [ ]:
B =np.array([( 1, 3, 1, 4),
             ( 3, 9, 5,15),
             ( 0, 2, 1, 1),
             ( 0, 4, 2, 3)])
#Tìm ma trận chuyển vị của B
B_T = B.T
print('Ma trận B:\n',B)
print('Ma trận chuyển vị của B:\n',B_T)

## THỰC HÀNH SỐ 5
---
**Yêu cầu: Học viên tìm ma trận nghịch đảo và hạng của ma trận Height, Weight trong bài thực hành số 4:**


In [ ]:
#{HỌC VIÊN VIÊT CODE VÀO ĐÂY}




