# Bài thực hành 2
### Môn: Linear Algebra

### Bài tập 1
Cho ma trận ${ A}=\left[\begin{matrix}
0 & 0 & 0\\
1 & 0 & 0\\
0 & 1 & 0
\end{matrix}\right]\ \ ;\ \ { B}=\left[\begin{matrix}
4 & -2 & 1\\
3 & 1 & -1\\
-1 & 5 & 0
\end{matrix}\right]$

* Chứng tỏ rằng ${A}^3=0$. Tính $({I}-{A})({I}+{A}+{A}^2)$.
* Tạo ma trận khối $C=\left[\begin{matrix}
A & I\\
-I & B
\end{matrix}\right]$. Tính định thức và hạng của $C$.

In [2]:
import numpy as np
print('Version', np.__version__)

Version 1.21.5


In [3]:
A = np.array([[0,0,0], [1,0,0], [0, 1, 0]])
B = np.array([[4, -2, 1], [3, 1, -1], [-1, 5, 0]])
A,B

(array([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]]),
 array([[ 4, -2,  1],
        [ 3,  1, -1],
        [-1,  5,  0]]))

In [5]:
#Chung to A^3 = 0
np.linalg.matrix_power(A,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
A@A@A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Tính T = (𝐼−𝐴)(𝐼+𝐴+𝐴2) .
T = (I-A)@(I+A+A@A)
T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#Tao ma tran khoi C
C1 = np.vstack([A, -I])
C2 = np.vstack([I,B])
C = np.hstack([C1,C2])
C

array([[ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  1.],
       [-1., -0., -0.,  4., -2.,  1.],
       [-0., -1., -0.,  3.,  1., -1.],
       [-0., -0., -1., -1.,  5.,  0.]])

In [17]:
#Tinh dinh thuc cua C
np.linalg.det(C)

-0.9999999999999998

In [18]:
#Tinh hang cuar C
np.linalg.matrix_rank(C)

6

### Bài tập 2
Lũy thừa ma trận có thể được sử dụng như một công cụ để phân tích trạng thái tới hạn của một số hệ động lực. Cho hai ma trận sau đây:

$${\bf A}=\left[\begin{matrix}
0.4 & 0.2 & 0.3\\
0.3 & 0.6 & 0.3\\
0.3 & 0.2 & 0.4
\end{matrix}\right],\,{\bf B}=\left[\begin{matrix}
0 & 0.2 & 0.3\\
0.1 & 0.6 & 0.3\\
0.9 & 0.2 & 0.4
\end{matrix}\right]$$

Hãy kiểm tra xem điều gì sẽ xảy ra với ${\bf A}^k$ và ${\bf B}^k$ khi $k$ nhận giá trị lớn.

In [23]:
A = np.array([0.4, 0.2, 0.3, 0.3, 0.6, 0.3, 0.3, 0.2, 0.4]).reshape(3,3)
B = np.array([0,0.2,0.3,0.1,0.6,0.3,0.9,0.2,0.4]).reshape(3,3)
A,B

(array([[0.4, 0.2, 0.3],
        [0.3, 0.6, 0.3],
        [0.3, 0.2, 0.4]]),
 array([[0. , 0.2, 0.3],
        [0.1, 0.6, 0.3],
        [0.9, 0.2, 0.4]]))

In [24]:
k = 10
print('A^k: \n', A**k)
print('B^k: \n', np.linalg.matrix_power(B, k))

A^k: 
 [[1.0485760e-04 1.0240000e-07 5.9049000e-06]
 [5.9049000e-06 6.0466176e-03 5.9049000e-06]
 [5.9049000e-06 1.0240000e-07 1.0485760e-04]]
B^k: 
 [[0.20226004 0.20224393 0.20224393]
 [0.37078055 0.37079665 0.37078055]
 [0.42695942 0.42695942 0.42697552]]


In [26]:
#Giá trị riêng và véc tơ riêng của A
np.linalg.eig(A)

(array([1. , 0.1, 0.3]),
 array([[-4.85071250e-01, -7.07106781e-01,  4.08248290e-01],
        [-7.27606875e-01,  2.38524432e-16, -8.16496581e-01],
        [-4.85071250e-01,  7.07106781e-01,  4.08248290e-01]]))

In [27]:
#Giá trị riêng  cua B
np.linalg.eig(B)

(array([-0.33166248,  0.33166248,  1.        ]),
 array([[ 0.59404463, -0.12024109, -0.33675758],
        [ 0.18808926,  0.75951783, -0.6173889 ],
        [-0.78213388, -0.63927674, -0.71093268]]))

### Bài 3
Phân tích ma trận đánh giá
$${\bf X}=\left[\begin{matrix}
3 & 3 & 0 & 4 & 4\\
0 & 5 & 2 & 0 & 1\\
2 & 0 & 1 & 2 & 5 \\
0 & 3 & 2 & 5 & 0 \\
2 & 5 & 0 & 3 & 2
\end{matrix}\right]
$$
thành tích $\bf W\,H^T$, với ${\bf W}\in\mathbb{R}^{5\times 3}$, ${\bf H}\in\mathbb{R}^{5\times 3}$. Sử dụng hàm mất mát dạng:
$$\mathcal{L}({\bf W},{\bf H})=\sum_{(u,i):x_{ui}\neq 0}\left(x_{ui}-\sum^3_{j=1}w_{uj}h_{ij}\right)^2$$

In [41]:
"""
@INPUT:
    A     : a matrix to be factorized, dimension M x N
    W     : an initial matrix of dimension M x K
    H     : an initial matrix of dimension N x K
    K     : the number of latent features
    steps : the maximum number of steps to perform the optimisation
    beta  : the learning rate
@OUTPUT:
    the final matrices W and H
"""

def matrix_factor(A, W, H, K, steps=5000, beta=0.0002):
    H = H.T
    for step in range(steps):
        for i in range(len(A)):
            for j in range(len(A[i])):
                if A[i][j] > 0:
                    eij = A[i][j] - np.dot(W[i,:],H[:,j])
                    for k in range(K):
                        W[i][k] = W[i][k] + beta*(2*eij*H[k][j])
                        H[k][j] = H[k][j] + beta*(2*eij*W[i][k])
        e = 0
        for i in range(len(A)):
            for j in range(len(A[i])):
                if A[i][j] > 0:
                    e = e + pow(A[i][j]-np.dot(W[i,:],H[:,j]), 2)
        if e < 0.0001:
            break
    return W, H.T

In [42]:
# Khởi tạo ma trận
A = np.array([[3,3,0,4,4],
              [0,5,2,0,1],
              [2,0,1,2,5],
              [0,3,2,5,0],
              [2,5,0,3,2]])

M = len(A)
N = len(A[0])
K = 3

W = np.random.rand(M,K)
H = np.random.rand(N,K)

# Phân tích ma trận
nW, nH = matrix_factor(A, W, H, K)
print(nW)
print(nH)
np.dot(nW,nH.T)

[[ 1.85706043  0.60370475  0.55648792]
 [ 0.53091511  0.42198455  1.98926202]
 [ 1.27628425  1.70257479 -0.01324591]
 [ 1.76124577 -0.24125027  1.2024427 ]
 [ 0.48945699  1.00810228  1.56645513]]
[[ 1.31858026  0.22661112  0.69072515]
 [ 0.50545806  1.48739334  2.06722263]
 [ 0.61125615  0.13513466  0.80763291]
 [ 1.78003205 -0.16853331  1.49072562]
 [ 1.71509428  1.6420867  -0.30710374]]


array([[2.96986964, 2.98699701, 1.66615899, 4.03345353, 4.00546974],
       [2.16971389, 5.00825981, 1.98814334, 3.83937133, 0.99259488],
       [2.05955631, 3.15012431, 0.99951561, 1.96514028, 4.9887911 ],
       [3.09823132, 3.01711859, 2.01510333, 4.96824476, 2.25527403],
       [1.95582547, 4.9850561 , 1.70053387, 3.03650512, 2.013792  ]])