### Bài 1
Cho ma trận: $A=\begin{pmatrix}
1 & 1 & 0\\
0 & 1 & 1\\
0 & 0 & -1
\end{pmatrix}$. Đặt: 

$$S(n)=I+A+A^2+\cdots+A^n$$ 

với $n\in\mathbb{N}_+$. Hãy tính $S(20)$ và $S(21)$. Có nhận xét gì về $\mathrm{det}(S_n)$.

In [37]:
import numpy as np 

A = np.array([[1,1,0],[0,1,1],[0,0,-1]])

In [67]:
def S(n):
    S = np.eye(3)
    for i in range(1,n+1):
        S+= np.power(A,i)
    return S

In [68]:
np.linalg.det(S(20))

441.0

In [69]:
np.linalg.det(S(21))

0.0

In [1]:
# đối với n là số lẻ thì det = 0 => ma trận không khả nghịch

### Bài 2
Giải hệ phương trình tuyến tính sau đây bằng phương pháp phân tích LU:

$$\left\{\begin{matrix}
x_1-2x_2+2x_3-x_4&=3\\
2x_1+4x_2-5x_3+x_4&=-1\\
-6x_1-x_2+3x_3+4x_4&=-3\\
4x_1+2x_2+x_3-8x_4&=4
\end{matrix}\right.$$

In [ ]:
# Ma trận hệ số
A = np.ara

### Bài 3
Trong không gian $\mathbb{R}^4$ cho không gian U có một cơ sở gồm các véc tơ:

$$u_1=\begin{pmatrix}
2 \\
-4 \\
1 \\
2
\end{pmatrix},\ \ u_2=\begin{pmatrix}
2\\
-9\\
-2\\
6
\end{pmatrix},\ \ u_3=\begin{pmatrix}
-2\\
-1\\
1\\
12
\end{pmatrix}$$

* Tìm một cơ sở trực chuẩn từ cơ sở trên của không gian $U$.
* Tính khoảng cách từ véc tơ $y=\begin{pmatrix}
4\\
17\\
2\\
4
\end{pmatrix}$ đến $U$.

### Bài 4
Tìm hàm hồi quy có dạng:

$$y=\beta_0+\beta_1\sin(x)+\beta_2\cos(x)$$

phù hợp nhất với bộ dữ liệu dưới đây:

| $x$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|---:|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|
| $y$ |3.23|-3.00|-3.84|-2.08|-0.93|4.52|10.94|6.44|-5.74|-7.52|

### Bài 5
Trong trường hợp hệ phương trình: $Ax=b$ có vô số nghiệm, nghiệm bình phương tối thiểu không xác định duy nhất. Khi đó người ta tìm nghiệm xấp xỉ có độ lớn nhỏ nhất bằng cách cực tiểu hóa hàm mục tiêu:

$$L(x)=\|Ax-b\|^2+\alpha\|x\|^2$$

Số hạng thứ hai trong hàm mục tiêu được gọi là số hiệu chỉnh. Trường hợp $\alpha=0$, nghiệm xấp xỉ chính là nghiệm bình phương tối thiểu. 

Tìm nghiệm xấp xỉ của hệ phương trình tuyến tính:

$$\begin{pmatrix}
-1 & 1 & 1\\
1 & -1 & -1\\
2 & 1 & -3
\end{pmatrix}x=\begin{pmatrix}
1 \\
-1 \\
0 
\end{pmatrix}$$

bằng phương pháp hiệu chỉnh với $\alpha=0.001$. Nhận xét về nghiệm xấp xỉ khi thay đổi giá trị của $\alpha$.

### Bài 6
Hàm $x(t)$ thỏa mãn phương trình vi phân:
$$L[x(t)]=\dfrac{d^2\,x}{dt^2}+e^t\dfrac{d\,x}{dt}+x=0$$
với điều kiện biên:
$$x(0)=0\ \ \hbox{và}\ \ x(2)=1$$
Theo phương pháp **`'collocation method'`**, nghiệm xấp xỉ của bài toán được tìm dưới dạng:
$$x(t)\approx x_n(t)=\sum^n_{i=0}\alpha_i\,t^{i}$$
thỏa mãn $x_n(0)=0$ và $x_n(2)=1$. Để xác định các hệ số $\alpha_i$, ta chọn $n-2$ điểm $t_j\in(0,2)$ sao cho $L[x_n(t_j)]=0$, với $j=1,\dots,n-2$.

Hãy tìm nghiệm xấp xỉ trong trường hợp $n=4$ và $t_1=0.5$, $t_2=1.0$, $t_3=1.5$.

- Nếu n = 4, t = 0: $\alpha_0 = 0$
- Nếu n = 4, t = 2: $\alpha_0 + 2\alpha_1 + 4\alpha_2 + 8\alpha_3 + 16\alpha_4=1$
- Ta có: $x_n(t) = \alpha_0 + \alpha_1t + \alpha_2t^2+\alpha_3t^3+\alpha_4t^4$

$\frac{dx_n(t)}{dt} = \alpha_1 + 2\alpha_2t + 3\alpha_3t^2+4\alpha_4t^3$

$\frac{d^2x_n(t)}{dt^2} = 2\alpha_2 + 6\alpha_3 t + 12\alpha_4 t^2$

$\Rightarrow 2\alpha_2 + 6\alpha_3 t + 12\alpha_4 t^2 + e^t(\alpha_1 + 2\alpha_2t + 3\alpha_3t^2+4\alpha_4t^3) + \alpha_0 + \alpha_1t + \alpha_2t^2+\alpha_3t^3+\alpha_4t^4 = 0$




$\Rightarrow \alpha_0 + \alpha_1(e^t+t) + \alpha_2(2+2te^t+t^2) + \alpha_3(6t+3t^2e^t+t^3)+\alpha_4(12t^2+4t^3e^t+t^4)=0$

In [12]:
import numpy as np

t = np.array([0.5, 1.0, 1.5])

X = np.vstack([np.ones(len(t)), np.exp(t) + t, 2 + 2*t*np.exp(t) + t **2,
              6*t+3*t**2*np.exp(t) + t**2, 12*t**2 + 4*t**3*np.exp(t) + t**4]).T

X = np.vstack([np.array([1, 0, 0, 0, 0]), X, np.array([1, 2, 4, 8, 16])])

print(X)

[[ 1.          0.          0.          0.          0.        ]
 [ 1.          2.14872127  3.89872127  4.48654095  3.88686064]
 [ 1.          3.71828183  8.43656366 15.15484549 23.87312731]
 [ 1.          5.98168907 17.69506721 41.50140122 92.56530245]
 [ 1.          2.          4.          8.         16.        ]]


In [ ]:
y = np.array([0, 0, 1.0, 1.5, 1])

In [ ]:
print("Nghiệm xấp xỉ là:")
np.linalg.lstsq(X, y)