In [12]:
import numpy as np
from scipy.linalg import lu

### Bài 1
Cho hai ma trận:
$$A=\begin{pmatrix}
1 & -7 & 4\\
2 & 0 & -3\\
-5 & 2 & 11
\end{pmatrix},\ \ B=\begin{pmatrix}
4 & 1 & -5\\
10 & -9 & 6\\
3 & 1 & 4
\end{pmatrix}$$
* Tính biểu thức: $(A+B)^2$ và $A^2+2AB+B^2$.
* Kết quả hai biểu thức có bằng nhau không? Giải thích tại sao?

In [2]:
A = np.array([[1, -7, 4], [2, 0, -3], [-5, 2, 11]])
B = np.array([[4, 1, -5], [10, -9, 6], [3, 1, 4]])

In [4]:
(A + B) ** 2

array([[ 25,  36,   1],
       [144,  81,   9],
       [  4,   9, 225]])

In [5]:
A @ A + 2 * A @ B + B @ B

array([[-130,  127,  -27],
       [ -17,   75, -149],
       [  44,   31,  264]])

Hai kết quả không giống nhau vì: $(A+B)^2=(A+B)(A+B)=A^2+AB+BA+B^2$

Mà $AB \neq BA$ do tích hai ma trận không có tính chất giao hoán


### Bài 2
Giải hệ phương trình tuyến tính sau đây bằng phương pháp ma trận nghịch đảo:

$$\left\{\begin{matrix}
2x_1+3x_2+4x_3+5x_4&=21\\
-5x_1+2x_2+3x_3+4x_4&=9\\
-4x_1-5x_2+2x_3+3x_4&=-7\\
-3x_1-4x_2-5x_3+2x_4&=-19
\end{matrix}\right.$$

In [6]:
A = np.array([[2, 3, 4, 5], [-5, 2, 3, 4], [-4, -5, 2, 3], [-3, -4, -5, 2]])
y = np.array([21, 9, -7, -19])

In [7]:
x = np.linalg.inv(A) @ y
print(x)

[1. 2. 2. 1.]


### Bài 3
Trong không gian $\mathbb{R}^4$ cho các véc tơ:

$$u_1=\begin{pmatrix}
1 \\
-2 \\
1 \\
3
\end{pmatrix},\ \ u_2=\begin{pmatrix}
2\\
4\\
1\\
5
\end{pmatrix},\ \ u_3=\begin{pmatrix}
8\\
0\\
-1\\
6
\end{pmatrix},\ \ u_4=\begin{pmatrix}
-3\\
6\\
4\\
7
\end{pmatrix} $$

Kí hiệu $U=\mathrm{Span\{u_1,u_2,u_3,u_4\}}$. Hỏi:
* Không gian $U$ có mấy chiều?
* Tìm một cơ sở của $U$.

In [8]:
u1 = np.array([1, -2, 1, 3])
u2 = np.array([2, 4, 1, 5])
u3 = np.array([8, 0, -1, 6])
u4 = np.array([-3, 6, 4, 7])

In [9]:
U = np.vstack([u1, u2, u3, u4]).T

In [11]:
print("Không gian U có {} chiều.".format(np.linalg.matrix_rank(U)))

Không gian U có 3 chiều.


In [13]:
u = lu(U)[2]
print(u)

[[ 3.          5.          6.          7.        ]
 [ 0.          7.33333333  4.         10.66666667]
 [ 0.          0.          5.81818182 -5.81818182]
 [ 0.          0.          0.          0.        ]]


In [14]:
print("Cơ sở trực của U là:", (u1, u2, u3))

Cơ sở trực của U là: (array([ 1, -2,  1,  3]), array([2, 4, 1, 5]), array([ 8,  0, -1,  6]))


### Bài 4
Trong không gian $\mathbb{R}^4$ cho không gian U có một cơ sở gồm các véc tơ:

$$u_1=\begin{pmatrix}
1 \\
-1 \\
2 \\
3
\end{pmatrix},\ \ u_2=\begin{pmatrix}
-1\\
2\\
3\\
4
\end{pmatrix},\ \ u_3=\begin{pmatrix}
4\\
-3\\
-2\\
4
\end{pmatrix}$$

* Tìm một cơ sở trực chuẩn từ cơ sở trên của không gian $U$.
* Tìm hình chiếu trực giao của véc tơ $y=\begin{pmatrix}
7\\
0\\
4\\
10
\end{pmatrix}$ trên $U$.

In [44]:
u1 = np.array([1, -1, 2, 3])
u2 = np.array([-1, 2, 3, 4])
u3 = np.array([4, -3, -2, 4])

v1 = u1
v2 = u2 - np.inner(u2, v1) / np.inner(v1, v1) * v1
v3 = u3 - (np.inner(u3, v1) / np.inner(v1, v1) * v1) - (np.inner(u3, v2) / np.inner(v2, v2) * v2)

v1 = v1/np.linalg.norm(v1)
v2 = v2/np.linalg.norm(v2)
v3 = v3/np.linalg.norm(v3)

In [45]:
print("Cơ sở trực chuẩn là:", (v1, v2, v3))

Cơ sở trực chuẩn là: (array([ 0.25819889, -0.25819889,  0.51639778,  0.77459667]), array([-0.51639778,  0.77459667,  0.25819889,  0.25819889]), array([ 0.25819889,  0.25819889, -0.77459667,  0.51639778]))


In [46]:
print(np.inner(v2, v3))

0.0


In [39]:
x1 = u1
x2 = u2
x3 = u3

# Thủ tục Gram-Schmidt
X = np.vstack([x1,x2,x3])
n = len(X)
A = [X[0]]      # orthonormal set

# Trực giao hóa
for i in range(1,n):
    u = X[i].copy()
    for v in A:
        if v.any()!=0:
            u = np.around(u-(np.inner(u,v)/np.inner(v,v))*v,10)
    if u.any()!=0:
        A.append(u)

# Trực chuẩn hóa
for i in range(len(A)):
    v = A[i]
    A[i] = np.around(1/np.linalg.norm(v)*v,10)
A=np.array(A)

print(A)
A[2] @ A[1]

[[ 0.25819889 -0.25819889  0.51639778  0.77459667]
 [-0.51639778  0.77459667  0.25819889  0.25819889]
 [ 0.25819889  0.25819889 -0.77459667  0.51639778]]


0.0

### Bài 5
Tìm hàm hồi quy có dạng:

$$y=\beta_0+\beta_1x+\beta_2\sin(x)$$

phù hợp nhất với bộ dữ liệu dưới đây:

| $x$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|---:|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|
| $y$ |5.82|13.04|14.39|13.71|17.60|26.22|33.67|33.51|37.82|37.39|

In [51]:
x = np.arange(1, 11)
X = np.vstack([np.ones(len(x)), x, np.sin(x)]).T
print(X)

[[ 1.          1.          0.84147098]
 [ 1.          2.          0.90929743]
 [ 1.          3.          0.14112001]
 [ 1.          4.         -0.7568025 ]
 [ 1.          5.         -0.95892427]
 [ 1.          6.         -0.2794155 ]
 [ 1.          7.          0.6569866 ]
 [ 1.          8.          0.98935825]
 [ 1.          9.          0.41211849]
 [ 1.         10.         -0.54402111]]


In [55]:
y = np.array([5.82, 13.04, 14.39, 13.71, 17.60, 26.22, 33.67, 33.51, 37.82, 37.39])

beta = np.linalg.lstsq(X, y)
print(beta[0])

[1.44301135 3.89670171 3.13302763]


C:\Users\phudn4\AppData\Local\Temp\ipykernel_21676\1033477492.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  beta = np.linalg.lstsq(X, y)


### Bài 6
Đối với hệ phương trình: $Ax=b$, ở đó ma trận hệ số $A$ có số điều kiện xấu, người ta tìm nghiệm xấp xỉ của hệ phương trình bằng cách cực tiểu hóa hàm mục tiêu:

$$L(x)=\|Ax-b\|^2+\alpha\|x\|^2$$

Số hạng thứ hai trong hàm mục tiêu được gọi là hiệu chỉnh. Trường hợp $\alpha=0$, nghiệm xấp xỉ chính là nghiệm bình phương tối thiểu. 

Xét hệ phương trình:

$$\begin{pmatrix}
1 & 2 & -1\\
3 & 5 & 2\\
1 & 2 & -1.001
\end{pmatrix}x=\begin{pmatrix}
-2 \\
0 \\
-1.99 
\end{pmatrix}$$

* Tìm nghiệm đúng của hệ phương trình. 
* Thay đổi ma trận hệ số một lượng nhỏ và tìm nghiệm. Rút ra nhận xét.
* Tìm nghiệm xấp xỉ của hệ phương trình bằng phương pháp hiệu chỉnh với $\alpha=0.001$.

In [56]:
A = np.array([[1, 2, -1], [3, 5, 2], [1, 2, -1.001]])
y = np.array([-2, 0, -1.99])

In [57]:
print("Nghiệm đúng của phương trình là:")
print(np.linalg.inv(A) @ y)

Nghiệm đúng của phương trình là:
[100. -56. -10.]


In [60]:
A_changed = np.array([[1.001, 1.9999, -1], [2.9988, 5.00001, 2], [1, 2, -1.001]])
print("Nghiệm sau khi thay đổi ma trận hệ số:")
print(np.linalg.inv(A_changed) @ y) 

Nghiệm sau khi thay đổi ma trận hệ số:
[-11.80099221   6.11284036   2.41227624]


Thay đổi nhỏ trên giá trị của ma trận hệ số làm nghiệm của phương trình thay đổi đáng kể

$L^{'}(x) = 2A^T(Ax-b) + 2\alpha x = 0$

$\Rightarrow (A^TA+\alpha I)x = A^Tb$

$\Rightarrow x = (A^TA +\alpha I)^{-1}A^Tb$

In [61]:
print("Nghiệm xấp xỉ là:")
print(np.linalg.inv(A.T@A+0.001 * np.eye(3)) @ A.T @ y)

Nghiệm xấp xỉ là:
[-0.09275737 -0.39162112  1.11808581]
