# Thực hành 1
### Môn: Linear Algebra

In [2]:
import numpy as np
print('Version: ', np.__version__)

Version:  1.21.5


In [11]:
a = np.ones((8,3))

In [12]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
b = np.full((3,4), 3.14)
b

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((2,2))

array([[0.40330214, 0.63810285],
       [0.32891327, 0.60712657]])

In [18]:
np.random.normal(0,1,(2,2))

array([[-0.34501375, -0.0600288 ],
       [-0.15746419,  0.55582977]])

In [20]:
np.random.randint(0,45,(3,3))

array([[17, 30,  4],
       [21, 16, 10],
       [31, 21,  0]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
A = np.random.randint(0,45, (2,3))
A

array([[39, 38, 44],
       [ 1, 33, 14]])

In [27]:
B = A [:, :2]
B

array([[39, 38],
       [ 1, 33]])

In [28]:
B[0,0] = 0

In [29]:
A #the fist element is changed

array([[ 0, 38, 44],
       [ 1, 33, 14]])

In [30]:
A_sub_copy = A[:, :2].copy()

In [31]:
A_sub_copy[0,0] = 1

In [32]:
A

array([[ 0, 38, 44],
       [ 1, 33, 14]])

In [33]:
x = np.arange(1,7)
print(x)
x.reshape((3,2))

[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
x = np.arange(2,8)
x.shape = (6,1)
x

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [37]:
x = np.array([5,5,5])
y = np.array([6,6,6])
np.concatenate([x,y])

array([5, 5, 5, 6, 6, 6])

In [40]:
a = np.zeros((2,3),dtype = int)
b = np.ones((2,3), dtype = int)
np.concatenate([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [41]:
np.concatenate([a,b], axis = 1)

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [42]:
np.vstack([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
np.hstack([a,b])

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [44]:
a

array([[0, 0, 0],
       [0, 0, 0]])

In [45]:
a.reshape(3,2)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [46]:
a

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
x = np.array([2,1,-4,3,5])
np.sort(x)

array([-4,  1,  2,  3,  5])

In [49]:
x

array([ 2,  1, -4,  3,  5])

In [51]:
np.argsort(x)

array([2, 1, 0, 3, 4], dtype=int64)

### Bài 1
* Tạo một mảng 2-chiều $a$ cỡ $10\times 10$, các phần tử hàng đầu tiên được khởi tạo ngẫu nhiên trong đoạn [-10,10]; các phần tử cột đầu tiên bằng $a[0,0]$; các phần tử cột cuối cùng bằng $a[0,9]$.
* Tính các phần tử còn lại được tính theo quy tắc: "*phần tử của hàng dưới bằng trung bình cộng của 3 phần tử gần nó nhất ở hàng trên*" (mô tả như hình vẽ trong phiếu bài tập)

In [60]:
A = np.zeros((10,10))
A[0,:] = np.random.randint(-10,10,10)
A[:,0] = A[0,0]
A[:,-1]= A[0,9]

In [61]:
A

array([[ 2.,  3.,  1., -4., -8., -2., -4., -2.,  6.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [ ]:
for i in range(1,9):
    for j in range(1,10)

### Bài 2
* Tạo một mảng 1 chiều $\bf x$ gồm $n=10$ số thực.
* Chọn 3 hàm số tùy ý $f_1(x),\,f_2(x),\,f_3(x)$.
* Tạo 3 mảng 1-chiều $y_1=[f_1(x)]$, $y_2=[f_2(x)]$, $y_3=[f_3(x)]$.
* Ghép bốn mảng 1-chiều thành một mảng 2-chiều kích thước $n\times 4$.

### Bài 3
* Tải dữ liệu từ file *heart$\_$rate.txt* vào mảng $a$.
* Thực hiện mô tả thống kê với các biến **Time** và **Heart Rate**: cỡ mẫu, trung bình, trung vị, độ lệch tiêu chuẩn, giá trị lớn nhất/nhỏ nhất, phần tư $Q_1,\,Q_2$ và $Q_3$.

In [67]:
a = np.loadtxt('heart_rate.txt', delimiter = ',', skiprows = 1)


In [77]:
#Time 
print('------Time-------')
print('Size:', a[:, 0].size)
print('Mean:', np.mean(a[:,0]) )
print('Median:', np.median(a[:,0]) )
print('Std:', np.std(a[:,0]) )
print('Max:', np.max(a[:,0]) )
print('Min:', np.min(a[:,0]) )

------Time-------
Size: 241
Mean: 600.0
Median: 600.0
Std: 347.85054261852173
Max: 1200.0
Min: 0.0


### Bài 4
* Ảnh *'towerbridge.jpg'* được biểu diễn bởi 1 tensor bậc 3 'arrcolor' bằng lệnh cho dưới đây.
* Chuyển thành ảnh xám bằng cách biến đổi tensor thành ma trận 'arrgray', mỗi phần tử là độ sáng của điểm ảnh bằng trung bình cộng các màu của điểm ảnh đó trong tensor. Tính và hiển thị ảnh xám ra màn hình.