## Bài tập 1.1:

In [ ]:
import numpy as np

In [ ]:
roll = np.random.randint(1, 7, 5000)
p1 = np.sum(roll == 4) / len(roll)
p2 = np.sum(roll >= 4) / len(roll)


p_6 = np.sum(roll == 6) / len(roll)
p_6_with_4 = (1 * p_6) / p2
print("Xác suất mặt 4 chấm: ", p1)
print("Xác suất mặt >= 4 chấm: ", p2)
print("Xác suất mặt 6 chấm khi biết số chấm >= 4: ", p_6_with_4)


Xác suất mặt 4 chấm:  0.1678
Xác suất mặt >= 4 chấm:  0.502
Xác suất mặt 6 chấm khi biết số chấm >= 4:  0.33386454183266934


### Bài tập 2.2:

In [ ]:
from sklearn import datasets

In [ ]:
iris_data = datasets.load_iris()
x = iris_data.data
y = iris_data.target
print("Number of samples: ", len(x))

Number of samples:  150


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
from sklearn import tree
classifier = tree.DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_test)

[0 2 0 1 1 0 0 0 0 2 2 1 0 0 0 1 0 0 0 1 0 1 0 2 1 2 0 2 1 0 0 2 1 1 2 2 0
 0 0 2 0 2 1 2 1]
[0 2 0 1 1 0 0 0 0 1 2 1 0 0 0 1 0 0 0 2 0 1 0 2 2 2 0 2 1 0 0 2 1 1 2 2 0
 0 0 2 0 2 1 2 1]


In [ ]:
# accuracy, precision, recall 
import numpy as np
from sklearn.metrics import recall_score, precision_score, confusion_matrix

# Precision 
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)
acc = np.sum(np.diag(conf_matrix)) / np.sum(conf_matrix)
print("Accuracy: {:.3f}".format(acc * 100))

precision = np.diag(conf_matrix) / np.sum(conf_matrix, axis=1)
print("Precision per class: ", precision)
print("Precision: ", np.mean(precision))
recall = np.diag(conf_matrix) / np.sum(conf_matrix, axis=0)
print("Recall per class: ", recall)
print("Recall: ", np.mean(recall))

[[21  0  0]
 [ 0 10  1]
 [ 0  2 11]]
Accuracy: 93.333
Precision per class:  [1.         0.90909091 0.84615385]
Precision:  0.9184149184149185
Recall per class:  [1.         0.83333333 0.91666667]
Recall:  0.9166666666666666
