# Bài thực hành 2
### Môn: Linear Algebra

In [2]:
import numpy as np
print('Version', np.__version__)

Version 1.21.5


### Bài tập 1
Cho ma trận ${ A}=\left[\begin{matrix}
0 & 0 & 0\\
1 & 0 & 0\\
0 & 1 & 0
\end{matrix}\right]\ \ ;\ \ { B}=\left[\begin{matrix}
4 & -2 & 1\\
3 & 1 & -1\\
-1 & 5 & 0
\end{matrix}\right]$

* Chứng tỏ rằng ${A}^3=0$. Tính $({I}-{A})({I}+{A}+{A}^2)$.
* Tạo ma trận khối $C=\left[\begin{matrix}
A & I\\
-I & B
\end{matrix}\right]$. Tính định thức và hạng của $C$.

In [3]:
A = np.array([[0,0,0], [1,0,0], [0, 1, 0]])
B = np.array([[4, -2, 1], [3, 1, -1], [-1, 5, 0]])

In [4]:
A

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [5]:
B

array([[ 4, -2,  1],
       [ 3,  1, -1],
       [-1,  5,  0]])

In [6]:
#Chung to A^3 = 0
np.linalg.matrix_power(A,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
A@A@A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
T = (I-A)@(I+A+A@A)
T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
C1 = np.vstack([A, -I])
C2 = np.vstack([I,B])
C = np.hstack([C1,C2])
C

array([[ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  1.],
       [-1., -0., -0.,  4., -2.,  1.],
       [-0., -1., -0.,  3.,  1., -1.],
       [-0., -0., -1., -1.,  5.,  0.]])

In [19]:
np.linalg.det(C)

-0.9999999999999998

In [21]:
np.linalg.matrix_rank(C)

6

### Bài tập 2
Lũy thừa ma trận có thể được sử dụng như một công cụ để phân tích trạng thái tới hạn của một số hệ động lực. Cho hai ma trận sau đây:

$${\bf A}=\left[\begin{matrix}
0.4 & 0.2 & 0.3\\
0.3 & 0.6 & 0.3\\
0.3 & 0.2 & 0.4
\end{matrix}\right],\,{\bf B}=\left[\begin{matrix}
0 & 0.2 & 0.3\\
0.1 & 0.6 & 0.3\\
0.9 & 0.2 & 0.4
\end{matrix}\right]$$

Hãy kiểm tra xem điều gì sẽ xảy ra với ${\bf A}^k$ và ${\bf B}^k$ khi $k$ nhận giá trị lớn.

In [23]:
A = np.array([0.4, 0.2, 0.3, 0.3, 0.6, 0.3, 0.3, 0.2, 0.4]).reshape(3,3)
A

array([[0.4, 0.2, 0.3],
       [0.3, 0.6, 0.3],
       [0.3, 0.2, 0.4]])

In [25]:
B = np.array([0, 0.2, 0.3, 0.1, 0.6, 0.3, 0.9, 0.2, 0.4]).reshape(3,3)
B

array([[0. , 0.2, 0.3],
       [0.1, 0.6, 0.3],
       [0.9, 0.2, 0.4]])

In [29]:
k = 1000
print('A^k: \n', np.linalg.matrix_power(A, k))
print('B^k: \n', np.linalg.matrix_power(B, k))

A^k: 
 [[0.28571429 0.28571429 0.28571429]
 [0.42857143 0.42857143 0.42857143]
 [0.28571429 0.28571429 0.28571429]]
B^k: 
 [[0.20224719 0.20224719 0.20224719]
 [0.37078652 0.37078652 0.37078652]
 [0.42696629 0.42696629 0.42696629]]


### Bài 3
Phân tích ma trận đánh giá
$${\bf X}=\left[\begin{matrix}
3 & 3 & 0 & 4 & 4\\
0 & 5 & 2 & 0 & 1\\
2 & 0 & 1 & 2 & 5 \\
0 & 3 & 2 & 5 & 0 \\
2 & 5 & 0 & 3 & 2
\end{matrix}\right]
$$
thành tích $\bf W\,H^T$, với ${\bf W}\in\mathbb{R}^{5\times 3}$, ${\bf H}\in\mathbb{R}^{5\times 3}$. Sử dụng hàm mất mát dạng:
$$\mathcal{L}({\bf W},{\bf H})=\sum_{(u,i):x_{ui}\neq 0}\left(x_{ui}-\sum^3_{j=1}w_{uj}h_{ij}\right)^2$$

In [30]:
steps = 1000
