# Bài thực hành 5
### Môn: Linear Algebra

In [1]:
import numpy as np
import scipy 

### Bài tập 1
Cho các véc tơ ${\bf x}_1=\left[\begin{matrix}
1 \\
5 \\
-6\\
3
\end{matrix}\right],\,{\bf x}_2=\left[\begin{matrix}
-3 \\
11 \\
-9 \\
12
\end{matrix}\right],\,{\bf x}_3=\left[\begin{matrix}
-10 \\
9 \\
-4 \\
4
\end{matrix}\right]$ và ${\bf y}=\left[\begin{matrix}
0 \\
0 \\
0 \\
-1
\end{matrix}\right]$. 
* Hãy xây dựng một cơ sở trực giao cho $W=\mathrm{span}\{{\bf x}_1,{\bf x}_2,{\bf x}_3\}$.
* Tìm hình chiếu trực giao của $\bf y$ trên $W$

In [2]:
v1 = np.array([1,-2,4,2])
v2 = np.array([4,1,5,-3])
v3 = np.array([1,-1,1,2])
v4 = np.array([-2,0,1,1])

In [3]:
np.inner(v1,v2)

16

### Bài tập 2

Cho ma trận: 
$${\bf A}=\left[\begin{matrix}
1 & 3 & -7\\
2 & 1 & 1\\
-2 & 7 & 11\\
9 & 11 & 3
\end{matrix}\right],\ 
{\bf b}=\left[\begin{matrix}
3\\
1\\
-1\\
3
\end{matrix}\right]$$
* Thực hiện phân tích QR cho ma trận ${\bf A}$.
* Tìm nghiệm bình phương cực tiểu của ${\bf A}{\bf x}={\bf b}$ bằng phân tích QR.
* Tìm một cơ sở trực chuẩn của không gian cột của $A$.

In [5]:
V = np.vstack([v1,v2,v3,v4]).T
V

array([[ 1,  4,  1, -2],
       [-2,  1, -1,  0],
       [ 4,  5,  1,  1],
       [ 2, -3,  2,  1]])

In [6]:
np.linalg.matrix_rank(V)


4

In [7]:
np.linalg.norm(v1)

5.0

In [8]:
#Goc giua hai vecto
cos_w12 = np.inner(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
cos_w12

0.4480896268889631

In [9]:
#Thuat toan truc chuan hoa gram-schmidt
a1 = v1
a2 = v2 - np.inner(v2,a1)/np.inner(a1,a1)*a1
a3 = v3 - np.inner(v3,a1)/np.inner(a1,a1)*a1\
        - np.inner(v3,a2)/np.inner(a2,a2)*a2
a4 = v4 - np.inner(v4,a1)/np.inner(a1,a1)*a1\
        - np.inner(v4,a2)/np.inner(a2,a2)*a2\
        - np.inner(v4,a3)/np.inner(a3,a3)*a3
print(a1,a2,a3,a4,sep='\n')

[ 1 -2  4  2]
[ 3.36  2.28  2.44 -4.28]
[ 0.97546614  0.16192345 -0.45829244  0.59077527]
[-0.30012771  0.99042146  0.33014049  0.48020434]


In [10]:
#Chuan hoa
e1 = a1/np.linalg.norm(a1)
e2 = a2/np.linalg.norm(a2)
e3 = a3/np.linalg.norm(a3)
e4 = a4/np.linalg.norm(a4)
print(e1,e2,e3,e4,sep = '\n')

[ 0.2 -0.4  0.8  0.4]
[ 0.52628645  0.35712295  0.38218421 -0.67038869]
[ 0.78687077  0.13061738 -0.36968677  0.47655554]
[-0.25269935  0.83390785  0.27796928  0.40431896]


In [11]:
#Kiem tra
np.inner(e1,e2)

-1.3877787807814457e-17

Giả thiết W = span{e1,e2,e3} cho x = (-5,2,4,2) .TÌm hình chiếu trực giao của x trên W

In [12]:
x = np.array([-5,2,4,2])
x_proj = np.inner(x,e1)*e1 + np.inner(x,e2)*e2 + np.inner(x,e3)*e3
x_proj



array([-3.77394636, -2.04597701,  2.651341  ,  0.03831418])

In [13]:
#Kiem tra 
x_res = x - x_proj
np.inner(x_res, x_proj)

-1.7763568394002505e-15

In [14]:
# Phân tích QR
A = np.array([1,0,0,1,1,0,1,1,1]).reshape(3,3)
A

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [15]:
Q,R = np.linalg.qr(A)
print("Q = " , Q)
print('R = ', R)

Q =  [[-5.77350269e-01  8.16496581e-01 -8.75605293e-17]
 [-5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01 -4.08248290e-01  7.07106781e-01]]
R =  [[-1.73205081 -1.15470054 -0.57735027]
 [ 0.         -0.81649658 -0.40824829]
 [ 0.          0.          0.70710678]]


In [18]:
#Bài toán 
A = np.array([1,3,-7,2,1,1,-2,7,11,9,11,3]).reshape(4,3)
A

array([[ 1,  3, -7],
       [ 2,  1,  1],
       [-2,  7, 11],
       [ 9, 11,  3]])

In [21]:
Q,R = np.linalg.qr(A)
print(Q,R,sep = '\n')

[[-0.10540926  0.21081851  0.9486833 ]
 [-0.21081851 -0.10540926 -0.21081851]
 [ 0.21081851  0.9486833  -0.21081851]
 [-0.9486833   0.21081851 -0.10540926]]
[[-9.48683298 -9.48683298  0.        ]
 [ 0.          9.48683298  9.48683298]
 [ 0.          0.         -9.48683298]]


In [23]:
b = np.array([3,1,-1,3])
np.linalg.lstsq(A,b,rcond = None)[0]

array([ 0.08888889,  0.28888889, -0.26666667])

In [24]:
np.linalg.inv(R)@Q.T@b

array([ 0.08888889,  0.28888889, -0.26666667])

### Bài 3 (Đo khoảng cách giữa các văn bản)

Mỗi văn bản được mô tả bởi 1 véc tơ $v\in\mathbb{R}^D$, ở đó $D$ là số lượng từ phân biệt có thể có. Mỗi thành phần toạ độ của $v$ tương ứng với 1 từ và ghi số từ có trong văn bản. Giả sử xét các đoạn văn bản sau:
> * $D_1$: *Tôi là An*.
> * $D_2$: *Tôi thích xem phim*.
> * $D_3$: *An là tên tôi*.
> * $D_4$: *Tôi rất thích đi du lịch, An là tên tôi*.

* Viết toạ độ của các văn bản trong không gian 11 chiều với toạ độ tương ứng với danh sách các từ sau:
> (*An, du, đi, là, lịch, phim, rất, tên, thích, tôi, xem*)
* Tính khoảng cách Euclide giữa các văn bản $D_1,D_2,D_3$, và $D_4$.
